### ISSUE TITLE
Outpainting? 

### ISSUE THREAD

**Issue by jadechip** [nosiu/InstantID-faceswap#2]
Thank you for sharing your work!
I've been able to product great results so far. Any idea on how this could be modified for outpainting?
...so that instantid generates a new person to the the right/left of the original image? 
I tried just changing the shape of the mask but judging by the results I think there is more to it 🤔

**Comment by nosiu** [comment]
Adding a new person would probably require running it for a second time with a new control image and mask in the desired location, probably even setting the mask_strength to 1:0 which will cause the two parts of the image not to blend well. 
Without GUI it would be veeeery hard to achieve.

I've tried to check how well it will work and well... it doesn't
[ComfyUI instantid faceswap](https://github.com/nosiu/comfyui-instantId-faceswap) was used as a GUI.
I pasted another face next to Einstein (because it was an easier solution) and masked the whole right side of the picture.
Mask even with 1 strength couldn't draw a good body, it might be possible to fix this with different parameters or by including some kind of visual prompt to the [masked area](https://github.com/InstantID/InstantID/pull/118) but honestly I don't know

![image](https://github.com/nosiu/InstantID-faceswap/assets/5691179/c45dbe6c-8ff2-48f3-b417-be49cb3441ca)
Result:
![image](https://github.com/nosiu/InstantID-faceswap/assets/5691179/594e068d-7cf4-4298-af4a-319e2815d5c1)
